---
title: 'Evangeline Reynolds'
author: ''
output:
  pdf_document: default
  html_document: default
header-includes:
- \usepackage{setspace}
- \setlength\parindent{0pt}
---


United States Miltary Academy
\vspace{-.2cm}

West Point, New York




\bigskip \bigskip



Dear Search Committee Members,

I am writing to apply for the position of Statistical Assistant.   

Until August 2023, I worked in the dual role of Data Manager and Assistant Professor at USMA.  In the role of Data Manager in the Dean's Data Cell, I worked closely with the Academic Departments, the G5, the registrar, and other members of the Dean's staff in fulfillment of external and internal reporting requirements and on self-assessment tasks.  

As Data Manager, I sought stakeholder input on reports to formulate standard, semi-automated products that clearly communicated information.  My work products aim to fully captures steps of analyses with reusable scripts that are well commented and coded to be robust, readable, and flexible.  Reports that I create extensive use of data visualization so that trends and patterns in the data are immediately apparent to the audience. When appropriate, I directly annotated visualizations with specific values or use accompanying tables to provide specificity. 

During my tenure in the data cell, I contributed to external reporting  on USMA faculty.  Reporting bodies included IPEDS, the Common Data Set, and ASEE.  For this task, we designed the decision rules and coordinated data pulls, cleaning, and joins for this enterprise. 

Also in the Dean's Data Cell, with colleagues, I explored dashboard redesign (PowerBI and Data Bricks) that would make real-time statistics more readily available and interprable to stakeholders and leadership.  I collaborated early on with many members of the USMA data community and other members of the Dean's staff on use interface as well as back end design. I would be happy to resume this work in the role of Statistical Assistant.  Additionally, my work in the Data Cell involved onboarding by orienting new Data Cell members to workflows, databases, reference materials, and relevant reporting concepts.   

My experience as an instructor in the math department would also serve as an asset in the role of Statistical Assistant. While teaching in the MA206 cohort, I cultivated relationships with faculty that will be an asset in terms of being able to quickly connect with a talented pool of experts on questions of tooling or statistical modeling techniques. 


<!-- Performs a variety of statistical assistant duties to include collecting, collating, tabulating and maintaining data used by the United States Military Academy. -->
<!-- Provides statistical support to a multi-disciplinary group by performing statistical based forecasts and depicting results of statistical calculations. -->
<!-- Inputs, changes, extracts, and stores data in applicable database or appropriate computer application. -->
<!-- Serves as lead integrator, data collector, and key holder for the Integrated Postsecondary Education Data System (IPEDS). -->
<!-- Prepares material in final form using automation software -->


<!-- From 2018-2020, I taught in the Master's in Security Studies track as a Visiting Teaching Assistant Professor at the Korbel School of International Studies at the University of Denver, with a teaching focus on research methodology. Given my research interests, professional background, teaching experience, and institutional knowledge of the Army and my substantial research support experience, I am well prepared for this position.  I would be excited to contribute to the Air Force Academy Political Science teaching team and to the Research Center through program and faculty development. -->

<!-- \emph{Teaching experience} -->

<!-- My teaching experience uniquely suits me to serve with the Political Science faculty.  After finishing my PhD at University of Illinois, I taught at the International Relations department at the Technische Universität, Dresden, I taught courses on international organizations, with substantial attention to security organizations.    -->

<!-- At Korbel, I taught for the International Security Master's track on methodology, where methodological readings were tailored to the security-interested student.   In the security-conscious environment of West Point, I've been involved in teaching Introduction to Probability and Statistics at West Point where military concerns are at the fore among analyses. -->

<!-- At Korbel, I would pleased to design specialized courses, as I did in Spring quarter 2020 at Korbel (Masters level course in data visualization), a skill which should serve our students well professionally. -->

<!-- The foundation for my trajectory in quantitative instruction was laid during my graduate studies when I worked a quantitative analysis consultant at the University of Illinois’ ATLAS lab (Applied Technologies for Learning in the Arts & Sciences) and working as the Political Science departmental methods teaching assistant for incoming PhD students.  Central to my role as TA was ensuring that up-to-date ``how-to'' skills helped students apply theoretical knowledge in the methods curriculum.   -->

<!-- I have applied this approach to pedagogy as well as I have learned how to use technology for effective online teaching.  .  -->

<!-- \emph{Areas of expertise for additional advanced classes} -->

<!-- I have several methodological areas of interests in which I can teach full courses. One of these is causal inference. My current courses survey regression discontinuity design, difference-in-difference design, natural experiments and randomized control trials. I would be happy to teach a full course on causal inference strategies which would also contain treatment of panel data and time series modeling.  -->

<!-- Other areas in which I could offer courses are text and network analysis --- topics that I currently introduce briefly in my classes. I have material to teach full 10 week courses on either of these topics or, due to their complementarity (network analysis is extensively used for text analysis), I could also conceive of a course combines these two areas.  Due to inherent relational nature of international relations and the verbal nature of social interaction, this adding tools in this area should be valuable to students.   -->

<!-- Another course offering could be on spatial analysis.  I have studied spatial analysis in graduate school in the University’s statistics department and I currently include a cursory treatment spatial data visualization, spatial dependence and modeling in my course Defense and Security Quantitative analysis.  I am also dedicating some of new grant resources to work in spatial visualization and analysis.  I could treat this topic in a more profound way by offering it as a full course, providing our students with insights and tools to contextualize and understand local and geopolitical dynamics.   -->

<!-- \emph{Research Support} -->

<!-- I have substantial experience supporting research. During my time at University of Denver, I advise my Security Masters’ students in preparing their research projects for the class using an in-person and one-on-one approach, and I have formally advised a student's directed research project this past summer. I have also counseled our PhD students, meeting an ABD student multiple times to provide guidance in analysis projects.  Moreover, I delivered a workshop for our PhD students on reproducible workflows in quantitative analysis this past fall. At West Point, I continued this mentoring practice, as I have involved two cadets in R programming projects that are on a trajectory to be high impact. I would be delighted to support colleagues and cadets as they pursue research at the U.S. Air Force Academy.  -->

<!-- Additionally, I have recently secured grant funding from the R Consortium to develop pedagogical statistical tools, with which I have hired three student research assistants with an additional two students involved. -->
<!-- Collaborating on this project will provide insights about quantitative tool development and about educating the public on its use (see “research” and my teaching statement for more on this project).  If I am hired, I would be glad to continue and extend my role in advising. -->


<!-- \emph{Public Service in Security} -->

<!-- My public service record bolsters my knowledge of real-world, security and technology policy in action, and gives me access to these worlds that I will bring into the Korbel classroom.  I've worked at a National Laboratory on Lithium Ion battery development for hybrid and electric car application through the 'Freedom Car' program; at the U.S. Department of Commerce (licensing officer enacting the requirements of the U.S. obligations under the Chemical Weapons Convention and the Australia Group which covers chemical and biological weapons precursors and dual-use items); and most recently for the US Military Academy at West Point in a dual role of Data Manager and Assistant Professor. As a data manager, I've worked to make the Academy's data reporting and analysis pipelines more insightful, robust, and auditable.  -->

<!-- Having a connection to these policy areas can be a boon for Korbel classrooms, because it will allow more interaction with people that have career trajectories of interest.  In teaching Advanced Data Visualization at Korbel, for example, I invited Berlin-based data communicator and computational ecologist, Cedric Scherer to reflect on his journey in data analytics and presentation.  I'm committed to continue to bring such expertise into my classroom if selected for a teaching role at Korbel.  -->



<!-- As teaching faculty, I would look forward to applying my leadership experience in more service and coordination at Korbel, especially in terms of developing the methodology curriculum.   For example, I believe there is potential for recruiting students from other departments into our undergraduate data science courses.  Last year, for my Data Science in International Relations course, we successfully recruited students from the business school and the data science master's program. We could expand to also recruit from political science and journalism. DU’s journalism department does not currently have on offer courses on data analysis.   -->


<!-- \emph{Research} -->

<!-- My research has focused on the application of statistically rigorous analysis in the area of international security.  I've used both randomization inference (for research on compliance with UN Security resolutions, and in methodological research to test false positive rates in dyadic difference in difference designs) and embedded survey experiments (surveying Brazilian congressional deputies about their attitudes toward international security law).  -->

<!-- Currently, my projects focus on advanced statistical programming that can bring important data and educational narratives to life for more compelling and deeper understanding.   -->


\bigskip


Thank you for your consideration of my application.



\noindent 

\bigskip
\noindent Kind regards, 

\vspace{.2cm}
\noindent Evangeline Reynolds, Ph.D.

------------



